// Code generated by Kitex v0.9.1. DO NOT EDIT.

package media

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	xuetang "xuetang/kitex_gen/xuetang"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryMediaFiles(ctx context.Context, req *xuetang.PageParams, callOptions ...callopt.Option) (r *xuetang.PageResult_, err error)
	UploadMediaFiles(ctx context.Context, req *xuetang.UploadFileParamsDto, filePath string, callOptions ...callopt.Option) (r *xuetang.UploadFileResultDto, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kMediaClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMediaClient struct {
	*kClient
}

func (p *kMediaClient) QueryMediaFiles(ctx context.Context, req *xuetang.PageParams, callOptions ...callopt.Option) (r *xuetang.PageResult_, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryMediaFiles(ctx, req)
}

func (p *kMediaClient) UploadMediaFiles(ctx context.Context, req *xuetang.UploadFileParamsDto, filePath string, callOptions ...callopt.Option) (r *xuetang.UploadFileResultDto, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadMediaFiles(ctx, req, filePath)
}
