// Code generated by thriftgo (0.3.10). DO NOT EDIT.

package xuetang

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"strings"
)

type MediaFiles struct {
	Id          string `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	CompanyId   int64  `thrift:"companyId,2,required" frugal:"2,required,i64" json:"companyId"`
	CompanyName string `thrift:"companyName,3,required" frugal:"3,required,string" json:"companyName"`
	Filename    string `thrift:"filename,4,required" frugal:"4,required,string" json:"filename"`
	FileType    string `thrift:"fileType,5,required" frugal:"5,required,string" json:"fileType"`
	Tags        string `thrift:"tags,6,required" frugal:"6,required,string" json:"tags"`
	Bucket      string `thrift:"bucket,7,required" frugal:"7,required,string" json:"bucket"`
	FilePath    string `thrift:"filePath,8,required" frugal:"8,required,string" json:"filePath"`
	FileId      string `thrift:"fileId,9,required" frugal:"9,required,string" json:"fileId"`
	Url         string `thrift:"url,10,required" frugal:"10,required,string" json:"url"`
	Username    string `thrift:"username,11,required" frugal:"11,required,string" json:"username"`
	CreateDate  string `thrift:"createDate,12,required" frugal:"12,required,string" json:"createDate"`
	ChangeDate  string `thrift:"changeDate,13,required" frugal:"13,required,string" json:"changeDate"`
	Status      string `thrift:"status,14,required" frugal:"14,required,string" json:"status"`
	Remark      string `thrift:"remark,15,required" frugal:"15,required,string" json:"remark"`
	AuditStatus string `thrift:"auditStatus,16,required" frugal:"16,required,string" json:"auditStatus"`
	AuditMind   string `thrift:"auditMind,17,required" frugal:"17,required,string" json:"auditMind"`
	FileSize    int64  `thrift:"fileSize,18,required" frugal:"18,required,i64" json:"fileSize"`
}

func NewMediaFiles() *MediaFiles {
	return &MediaFiles{}
}

func (p *MediaFiles) InitDefault() {
	*p = MediaFiles{}
}

func (p *MediaFiles) GetId() (v string) {
	return p.Id
}

func (p *MediaFiles) GetCompanyId() (v int64) {
	return p.CompanyId
}

func (p *MediaFiles) GetCompanyName() (v string) {
	return p.CompanyName
}

func (p *MediaFiles) GetFilename() (v string) {
	return p.Filename
}

func (p *MediaFiles) GetFileType() (v string) {
	return p.FileType
}

func (p *MediaFiles) GetTags() (v string) {
	return p.Tags
}

func (p *MediaFiles) GetBucket() (v string) {
	return p.Bucket
}

func (p *MediaFiles) GetFilePath() (v string) {
	return p.FilePath
}

func (p *MediaFiles) GetFileId() (v string) {
	return p.FileId
}

func (p *MediaFiles) GetUrl() (v string) {
	return p.Url
}

func (p *MediaFiles) GetUsername() (v string) {
	return p.Username
}

func (p *MediaFiles) GetCreateDate() (v string) {
	return p.CreateDate
}

func (p *MediaFiles) GetChangeDate() (v string) {
	return p.ChangeDate
}

func (p *MediaFiles) GetStatus() (v string) {
	return p.Status
}

func (p *MediaFiles) GetRemark() (v string) {
	return p.Remark
}

func (p *MediaFiles) GetAuditStatus() (v string) {
	return p.AuditStatus
}

func (p *MediaFiles) GetAuditMind() (v string) {
	return p.AuditMind
}

func (p *MediaFiles) GetFileSize() (v int64) {
	return p.FileSize
}
func (p *MediaFiles) SetId(val string) {
	p.Id = val
}
func (p *MediaFiles) SetCompanyId(val int64) {
	p.CompanyId = val
}
func (p *MediaFiles) SetCompanyName(val string) {
	p.CompanyName = val
}
func (p *MediaFiles) SetFilename(val string) {
	p.Filename = val
}
func (p *MediaFiles) SetFileType(val string) {
	p.FileType = val
}
func (p *MediaFiles) SetTags(val string) {
	p.Tags = val
}
func (p *MediaFiles) SetBucket(val string) {
	p.Bucket = val
}
func (p *MediaFiles) SetFilePath(val string) {
	p.FilePath = val
}
func (p *MediaFiles) SetFileId(val string) {
	p.FileId = val
}
func (p *MediaFiles) SetUrl(val string) {
	p.Url = val
}
func (p *MediaFiles) SetUsername(val string) {
	p.Username = val
}
func (p *MediaFiles) SetCreateDate(val string) {
	p.CreateDate = val
}
func (p *MediaFiles) SetChangeDate(val string) {
	p.ChangeDate = val
}
func (p *MediaFiles) SetStatus(val string) {
	p.Status = val
}
func (p *MediaFiles) SetRemark(val string) {
	p.Remark = val
}
func (p *MediaFiles) SetAuditStatus(val string) {
	p.AuditStatus = val
}
func (p *MediaFiles) SetAuditMind(val string) {
	p.AuditMind = val
}
func (p *MediaFiles) SetFileSize(val int64) {
	p.FileSize = val
}

var fieldIDToName_MediaFiles = map[int16]string{
	1:  "id",
	2:  "companyId",
	3:  "companyName",
	4:  "filename",
	5:  "fileType",
	6:  "tags",
	7:  "bucket",
	8:  "filePath",
	9:  "fileId",
	10: "url",
	11: "username",
	12: "createDate",
	13: "changeDate",
	14: "status",
	15: "remark",
	16: "auditStatus",
	17: "auditMind",
	18: "fileSize",
}

func (p *MediaFiles) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetId bool = false
	var issetCompanyId bool = false
	var issetCompanyName bool = false
	var issetFilename bool = false
	var issetFileType bool = false
	var issetTags bool = false
	var issetBucket bool = false
	var issetFilePath bool = false
	var issetFileId bool = false
	var issetUrl bool = false
	var issetUsername bool = false
	var issetCreateDate bool = false
	var issetChangeDate bool = false
	var issetStatus bool = false
	var issetRemark bool = false
	var issetAuditStatus bool = false
	var issetAuditMind bool = false
	var issetFileSize bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetId = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetCompanyId = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetCompanyName = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetFilename = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
				issetFileType = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
				issetTags = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
				issetBucket = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 8:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField8(iprot); err != nil {
					goto ReadFieldError
				}
				issetFilePath = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 9:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField9(iprot); err != nil {
					goto ReadFieldError
				}
				issetFileId = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 10:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField10(iprot); err != nil {
					goto ReadFieldError
				}
				issetUrl = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 11:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField11(iprot); err != nil {
					goto ReadFieldError
				}
				issetUsername = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 12:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField12(iprot); err != nil {
					goto ReadFieldError
				}
				issetCreateDate = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 13:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField13(iprot); err != nil {
					goto ReadFieldError
				}
				issetChangeDate = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 14:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField14(iprot); err != nil {
					goto ReadFieldError
				}
				issetStatus = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 15:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField15(iprot); err != nil {
					goto ReadFieldError
				}
				issetRemark = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 16:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField16(iprot); err != nil {
					goto ReadFieldError
				}
				issetAuditStatus = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 17:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField17(iprot); err != nil {
					goto ReadFieldError
				}
				issetAuditMind = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 18:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField18(iprot); err != nil {
					goto ReadFieldError
				}
				issetFileSize = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetId {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetCompanyId {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetCompanyName {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetFilename {
		fieldId = 4
		goto RequiredFieldNotSetError
	}

	if !issetFileType {
		fieldId = 5
		goto RequiredFieldNotSetError
	}

	if !issetTags {
		fieldId = 6
		goto RequiredFieldNotSetError
	}

	if !issetBucket {
		fieldId = 7
		goto RequiredFieldNotSetError
	}

	if !issetFilePath {
		fieldId = 8
		goto RequiredFieldNotSetError
	}

	if !issetFileId {
		fieldId = 9
		goto RequiredFieldNotSetError
	}

	if !issetUrl {
		fieldId = 10
		goto RequiredFieldNotSetError
	}

	if !issetUsername {
		fieldId = 11
		goto RequiredFieldNotSetError
	}

	if !issetCreateDate {
		fieldId = 12
		goto RequiredFieldNotSetError
	}

	if !issetChangeDate {
		fieldId = 13
		goto RequiredFieldNotSetError
	}

	if !issetStatus {
		fieldId = 14
		goto RequiredFieldNotSetError
	}

	if !issetRemark {
		fieldId = 15
		goto RequiredFieldNotSetError
	}

	if !issetAuditStatus {
		fieldId = 16
		goto RequiredFieldNotSetError
	}

	if !issetAuditMind {
		fieldId = 17
		goto RequiredFieldNotSetError
	}

	if !issetFileSize {
		fieldId = 18
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MediaFiles[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_MediaFiles[fieldId]))
}

func (p *MediaFiles) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Id = v
	}
	return nil
}
func (p *MediaFiles) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.CompanyId = v
	}
	return nil
}
func (p *MediaFiles) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.CompanyName = v
	}
	return nil
}
func (p *MediaFiles) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Filename = v
	}
	return nil
}
func (p *MediaFiles) ReadField5(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FileType = v
	}
	return nil
}
func (p *MediaFiles) ReadField6(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Tags = v
	}
	return nil
}
func (p *MediaFiles) ReadField7(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Bucket = v
	}
	return nil
}
func (p *MediaFiles) ReadField8(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FilePath = v
	}
	return nil
}
func (p *MediaFiles) ReadField9(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FileId = v
	}
	return nil
}
func (p *MediaFiles) ReadField10(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Url = v
	}
	return nil
}
func (p *MediaFiles) ReadField11(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Username = v
	}
	return nil
}
func (p *MediaFiles) ReadField12(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.CreateDate = v
	}
	return nil
}
func (p *MediaFiles) ReadField13(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.ChangeDate = v
	}
	return nil
}
func (p *MediaFiles) ReadField14(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Status = v
	}
	return nil
}
func (p *MediaFiles) ReadField15(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Remark = v
	}
	return nil
}
func (p *MediaFiles) ReadField16(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.AuditStatus = v
	}
	return nil
}
func (p *MediaFiles) ReadField17(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.AuditMind = v
	}
	return nil
}
func (p *MediaFiles) ReadField18(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.FileSize = v
	}
	return nil
}

func (p *MediaFiles) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("MediaFiles"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
		if err = p.writeField8(oprot); err != nil {
			fieldId = 8
			goto WriteFieldError
		}
		if err = p.writeField9(oprot); err != nil {
			fieldId = 9
			goto WriteFieldError
		}
		if err = p.writeField10(oprot); err != nil {
			fieldId = 10
			goto WriteFieldError
		}
		if err = p.writeField11(oprot); err != nil {
			fieldId = 11
			goto WriteFieldError
		}
		if err = p.writeField12(oprot); err != nil {
			fieldId = 12
			goto WriteFieldError
		}
		if err = p.writeField13(oprot); err != nil {
			fieldId = 13
			goto WriteFieldError
		}
		if err = p.writeField14(oprot); err != nil {
			fieldId = 14
			goto WriteFieldError
		}
		if err = p.writeField15(oprot); err != nil {
			fieldId = 15
			goto WriteFieldError
		}
		if err = p.writeField16(oprot); err != nil {
			fieldId = 16
			goto WriteFieldError
		}
		if err = p.writeField17(oprot); err != nil {
			fieldId = 17
			goto WriteFieldError
		}
		if err = p.writeField18(oprot); err != nil {
			fieldId = 18
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MediaFiles) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Id); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MediaFiles) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("companyId", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.CompanyId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *MediaFiles) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("companyName", thrift.STRING, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.CompanyName); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *MediaFiles) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("filename", thrift.STRING, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Filename); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *MediaFiles) writeField5(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("fileType", thrift.STRING, 5); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FileType); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *MediaFiles) writeField6(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("tags", thrift.STRING, 6); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Tags); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *MediaFiles) writeField7(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("bucket", thrift.STRING, 7); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Bucket); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *MediaFiles) writeField8(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("filePath", thrift.STRING, 8); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FilePath); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 8 end error: ", p), err)
}

func (p *MediaFiles) writeField9(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("fileId", thrift.STRING, 9); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FileId); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 9 end error: ", p), err)
}

func (p *MediaFiles) writeField10(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("url", thrift.STRING, 10); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Url); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 10 end error: ", p), err)
}

func (p *MediaFiles) writeField11(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("username", thrift.STRING, 11); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Username); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 11 end error: ", p), err)
}

func (p *MediaFiles) writeField12(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("createDate", thrift.STRING, 12); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.CreateDate); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 12 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 12 end error: ", p), err)
}

func (p *MediaFiles) writeField13(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("changeDate", thrift.STRING, 13); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.ChangeDate); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 13 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 13 end error: ", p), err)
}

func (p *MediaFiles) writeField14(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("status", thrift.STRING, 14); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Status); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 14 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 14 end error: ", p), err)
}

func (p *MediaFiles) writeField15(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("remark", thrift.STRING, 15); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Remark); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 15 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 15 end error: ", p), err)
}

func (p *MediaFiles) writeField16(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("auditStatus", thrift.STRING, 16); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.AuditStatus); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 16 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 16 end error: ", p), err)
}

func (p *MediaFiles) writeField17(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("auditMind", thrift.STRING, 17); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.AuditMind); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 17 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 17 end error: ", p), err)
}

func (p *MediaFiles) writeField18(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("fileSize", thrift.I64, 18); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.FileSize); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 18 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 18 end error: ", p), err)
}

func (p *MediaFiles) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MediaFiles(%+v)", *p)

}

func (p *MediaFiles) DeepEqual(ano *MediaFiles) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Id) {
		return false
	}
	if !p.Field2DeepEqual(ano.CompanyId) {
		return false
	}
	if !p.Field3DeepEqual(ano.CompanyName) {
		return false
	}
	if !p.Field4DeepEqual(ano.Filename) {
		return false
	}
	if !p.Field5DeepEqual(ano.FileType) {
		return false
	}
	if !p.Field6DeepEqual(ano.Tags) {
		return false
	}
	if !p.Field7DeepEqual(ano.Bucket) {
		return false
	}
	if !p.Field8DeepEqual(ano.FilePath) {
		return false
	}
	if !p.Field9DeepEqual(ano.FileId) {
		return false
	}
	if !p.Field10DeepEqual(ano.Url) {
		return false
	}
	if !p.Field11DeepEqual(ano.Username) {
		return false
	}
	if !p.Field12DeepEqual(ano.CreateDate) {
		return false
	}
	if !p.Field13DeepEqual(ano.ChangeDate) {
		return false
	}
	if !p.Field14DeepEqual(ano.Status) {
		return false
	}
	if !p.Field15DeepEqual(ano.Remark) {
		return false
	}
	if !p.Field16DeepEqual(ano.AuditStatus) {
		return false
	}
	if !p.Field17DeepEqual(ano.AuditMind) {
		return false
	}
	if !p.Field18DeepEqual(ano.FileSize) {
		return false
	}
	return true
}

func (p *MediaFiles) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Id, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field2DeepEqual(src int64) bool {

	if p.CompanyId != src {
		return false
	}
	return true
}
func (p *MediaFiles) Field3DeepEqual(src string) bool {

	if strings.Compare(p.CompanyName, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Filename, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field5DeepEqual(src string) bool {

	if strings.Compare(p.FileType, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Tags, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field7DeepEqual(src string) bool {

	if strings.Compare(p.Bucket, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field8DeepEqual(src string) bool {

	if strings.Compare(p.FilePath, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field9DeepEqual(src string) bool {

	if strings.Compare(p.FileId, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field10DeepEqual(src string) bool {

	if strings.Compare(p.Url, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field11DeepEqual(src string) bool {

	if strings.Compare(p.Username, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field12DeepEqual(src string) bool {

	if strings.Compare(p.CreateDate, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field13DeepEqual(src string) bool {

	if strings.Compare(p.ChangeDate, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field14DeepEqual(src string) bool {

	if strings.Compare(p.Status, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field15DeepEqual(src string) bool {

	if strings.Compare(p.Remark, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field16DeepEqual(src string) bool {

	if strings.Compare(p.AuditStatus, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field17DeepEqual(src string) bool {

	if strings.Compare(p.AuditMind, src) != 0 {
		return false
	}
	return true
}
func (p *MediaFiles) Field18DeepEqual(src int64) bool {

	if p.FileSize != src {
		return false
	}
	return true
}

type PageParams struct {
	PageNo   int64 `thrift:"pageNo,1,required" frugal:"1,required,i64" json:"pageNo"`
	PageSize int64 `thrift:"pageSize,2,required" frugal:"2,required,i64" json:"pageSize"`
}

func NewPageParams() *PageParams {
	return &PageParams{}
}

func (p *PageParams) InitDefault() {
	*p = PageParams{}
}

func (p *PageParams) GetPageNo() (v int64) {
	return p.PageNo
}

func (p *PageParams) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *PageParams) SetPageNo(val int64) {
	p.PageNo = val
}
func (p *PageParams) SetPageSize(val int64) {
	p.PageSize = val
}

var fieldIDToName_PageParams = map[int16]string{
	1: "pageNo",
	2: "pageSize",
}

func (p *PageParams) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetPageNo bool = false
	var issetPageSize bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetPageNo = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetPageSize = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetPageNo {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetPageSize {
		fieldId = 2
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageParams[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_PageParams[fieldId]))
}

func (p *PageParams) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.PageNo = v
	}
	return nil
}
func (p *PageParams) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.PageSize = v
	}
	return nil
}

func (p *PageParams) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PageParams"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageParams) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("pageNo", thrift.I64, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.PageNo); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PageParams) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("pageSize", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.PageSize); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageParams) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageParams(%+v)", *p)

}

func (p *PageParams) DeepEqual(ano *PageParams) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.PageNo) {
		return false
	}
	if !p.Field2DeepEqual(ano.PageSize) {
		return false
	}
	return true
}

func (p *PageParams) Field1DeepEqual(src int64) bool {

	if p.PageNo != src {
		return false
	}
	return true
}
func (p *PageParams) Field2DeepEqual(src int64) bool {

	if p.PageSize != src {
		return false
	}
	return true
}

type PageResult_ struct {
	Items    []*MediaFiles `thrift:"items,1,required" frugal:"1,required,list<MediaFiles>" json:"items"`
	Counts   int64         `thrift:"counts,2,required" frugal:"2,required,i64" json:"counts"`
	Page     int64         `thrift:"page,3,required" frugal:"3,required,i64" json:"page"`
	PageSize int64         `thrift:"pageSize,4,required" frugal:"4,required,i64" json:"pageSize"`
}

func NewPageResult_() *PageResult_ {
	return &PageResult_{}
}

func (p *PageResult_) InitDefault() {
	*p = PageResult_{}
}

func (p *PageResult_) GetItems() (v []*MediaFiles) {
	return p.Items
}

func (p *PageResult_) GetCounts() (v int64) {
	return p.Counts
}

func (p *PageResult_) GetPage() (v int64) {
	return p.Page
}

func (p *PageResult_) GetPageSize() (v int64) {
	return p.PageSize
}
func (p *PageResult_) SetItems(val []*MediaFiles) {
	p.Items = val
}
func (p *PageResult_) SetCounts(val int64) {
	p.Counts = val
}
func (p *PageResult_) SetPage(val int64) {
	p.Page = val
}
func (p *PageResult_) SetPageSize(val int64) {
	p.PageSize = val
}

var fieldIDToName_PageResult_ = map[int16]string{
	1: "items",
	2: "counts",
	3: "page",
	4: "pageSize",
}

func (p *PageResult_) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetItems bool = false
	var issetCounts bool = false
	var issetPage bool = false
	var issetPageSize bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetItems = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetCounts = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetPage = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetPageSize = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetItems {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetCounts {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetPage {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetPageSize {
		fieldId = 4
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PageResult_[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_PageResult_[fieldId]))
}

func (p *PageResult_) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return err
	}
	p.Items = make([]*MediaFiles, 0, size)
	for i := 0; i < size; i++ {
		_elem := NewMediaFiles()
		if err := _elem.Read(iprot); err != nil {
			return err
		}

		p.Items = append(p.Items, _elem)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return err
	}
	return nil
}
func (p *PageResult_) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.Counts = v
	}
	return nil
}
func (p *PageResult_) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.Page = v
	}
	return nil
}
func (p *PageResult_) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.PageSize = v
	}
	return nil
}

func (p *PageResult_) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PageResult"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PageResult_) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("items", thrift.LIST, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Items)); err != nil {
		return err
	}
	for _, v := range p.Items {
		if err := v.Write(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PageResult_) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("counts", thrift.I64, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Counts); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PageResult_) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("page", thrift.I64, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.Page); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *PageResult_) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("pageSize", thrift.I64, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.PageSize); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *PageResult_) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PageResult_(%+v)", *p)

}

func (p *PageResult_) DeepEqual(ano *PageResult_) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Items) {
		return false
	}
	if !p.Field2DeepEqual(ano.Counts) {
		return false
	}
	if !p.Field3DeepEqual(ano.Page) {
		return false
	}
	if !p.Field4DeepEqual(ano.PageSize) {
		return false
	}
	return true
}

func (p *PageResult_) Field1DeepEqual(src []*MediaFiles) bool {

	if len(p.Items) != len(src) {
		return false
	}
	for i, v := range p.Items {
		_src := src[i]
		if !v.DeepEqual(_src) {
			return false
		}
	}
	return true
}
func (p *PageResult_) Field2DeepEqual(src int64) bool {

	if p.Counts != src {
		return false
	}
	return true
}
func (p *PageResult_) Field3DeepEqual(src int64) bool {

	if p.Page != src {
		return false
	}
	return true
}
func (p *PageResult_) Field4DeepEqual(src int64) bool {

	if p.PageSize != src {
		return false
	}
	return true
}

type UploadFileParamsDto struct {
	Filename string `thrift:"filename,1,required" frugal:"1,required,string" json:"filename"`
	FileType string `thrift:"fileType,2,required" frugal:"2,required,string" json:"fileType"`
	FileSize int64  `thrift:"fileSize,3,required" frugal:"3,required,i64" json:"fileSize"`
	Tags     string `thrift:"tags,4,required" frugal:"4,required,string" json:"tags"`
	Username string `thrift:"username,5,required" frugal:"5,required,string" json:"username"`
	Remark   string `thrift:"remark,6,required" frugal:"6,required,string" json:"remark"`
}

func NewUploadFileParamsDto() *UploadFileParamsDto {
	return &UploadFileParamsDto{}
}

func (p *UploadFileParamsDto) InitDefault() {
	*p = UploadFileParamsDto{}
}

func (p *UploadFileParamsDto) GetFilename() (v string) {
	return p.Filename
}

func (p *UploadFileParamsDto) GetFileType() (v string) {
	return p.FileType
}

func (p *UploadFileParamsDto) GetFileSize() (v int64) {
	return p.FileSize
}

func (p *UploadFileParamsDto) GetTags() (v string) {
	return p.Tags
}

func (p *UploadFileParamsDto) GetUsername() (v string) {
	return p.Username
}

func (p *UploadFileParamsDto) GetRemark() (v string) {
	return p.Remark
}
func (p *UploadFileParamsDto) SetFilename(val string) {
	p.Filename = val
}
func (p *UploadFileParamsDto) SetFileType(val string) {
	p.FileType = val
}
func (p *UploadFileParamsDto) SetFileSize(val int64) {
	p.FileSize = val
}
func (p *UploadFileParamsDto) SetTags(val string) {
	p.Tags = val
}
func (p *UploadFileParamsDto) SetUsername(val string) {
	p.Username = val
}
func (p *UploadFileParamsDto) SetRemark(val string) {
	p.Remark = val
}

var fieldIDToName_UploadFileParamsDto = map[int16]string{
	1: "filename",
	2: "fileType",
	3: "fileSize",
	4: "tags",
	5: "username",
	6: "remark",
}

func (p *UploadFileParamsDto) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetFilename bool = false
	var issetFileType bool = false
	var issetFileSize bool = false
	var issetTags bool = false
	var issetUsername bool = false
	var issetRemark bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetFilename = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
				issetFileType = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.I64 {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
				issetFileSize = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
				issetTags = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
				issetUsername = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
				issetRemark = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetFilename {
		fieldId = 1
		goto RequiredFieldNotSetError
	}

	if !issetFileType {
		fieldId = 2
		goto RequiredFieldNotSetError
	}

	if !issetFileSize {
		fieldId = 3
		goto RequiredFieldNotSetError
	}

	if !issetTags {
		fieldId = 4
		goto RequiredFieldNotSetError
	}

	if !issetUsername {
		fieldId = 5
		goto RequiredFieldNotSetError
	}

	if !issetRemark {
		fieldId = 6
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_UploadFileParamsDto[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_UploadFileParamsDto[fieldId]))
}

func (p *UploadFileParamsDto) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Filename = v
	}
	return nil
}
func (p *UploadFileParamsDto) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FileType = v
	}
	return nil
}
func (p *UploadFileParamsDto) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI64(); err != nil {
		return err
	} else {
		p.FileSize = v
	}
	return nil
}
func (p *UploadFileParamsDto) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Tags = v
	}
	return nil
}
func (p *UploadFileParamsDto) ReadField5(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Username = v
	}
	return nil
}
func (p *UploadFileParamsDto) ReadField6(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Remark = v
	}
	return nil
}

func (p *UploadFileParamsDto) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UploadFileParamsDto"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("filename", thrift.STRING, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Filename); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("fileType", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FileType); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField3(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("fileSize", thrift.I64, 3); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteI64(p.FileSize); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField4(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("tags", thrift.STRING, 4); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Tags); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField5(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("username", thrift.STRING, 5); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Username); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *UploadFileParamsDto) writeField6(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("remark", thrift.STRING, 6); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.Remark); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *UploadFileParamsDto) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadFileParamsDto(%+v)", *p)

}

func (p *UploadFileParamsDto) DeepEqual(ano *UploadFileParamsDto) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Filename) {
		return false
	}
	if !p.Field2DeepEqual(ano.FileType) {
		return false
	}
	if !p.Field3DeepEqual(ano.FileSize) {
		return false
	}
	if !p.Field4DeepEqual(ano.Tags) {
		return false
	}
	if !p.Field5DeepEqual(ano.Username) {
		return false
	}
	if !p.Field6DeepEqual(ano.Remark) {
		return false
	}
	return true
}

func (p *UploadFileParamsDto) Field1DeepEqual(src string) bool {

	if strings.Compare(p.Filename, src) != 0 {
		return false
	}
	return true
}
func (p *UploadFileParamsDto) Field2DeepEqual(src string) bool {

	if strings.Compare(p.FileType, src) != 0 {
		return false
	}
	return true
}
func (p *UploadFileParamsDto) Field3DeepEqual(src int64) bool {

	if p.FileSize != src {
		return false
	}
	return true
}
func (p *UploadFileParamsDto) Field4DeepEqual(src string) bool {

	if strings.Compare(p.Tags, src) != 0 {
		return false
	}
	return true
}
func (p *UploadFileParamsDto) Field5DeepEqual(src string) bool {

	if strings.Compare(p.Username, src) != 0 {
		return false
	}
	return true
}
func (p *UploadFileParamsDto) Field6DeepEqual(src string) bool {

	if strings.Compare(p.Remark, src) != 0 {
		return false
	}
	return true
}

type UploadFileResultDto struct {
	MediaFiles *MediaFiles `thrift:"mediaFiles,1" frugal:"1,default,MediaFiles" json:"mediaFiles"`
}

func NewUploadFileResultDto() *UploadFileResultDto {
	return &UploadFileResultDto{}
}

func (p *UploadFileResultDto) InitDefault() {
	*p = UploadFileResultDto{}
}

var UploadFileResultDto_MediaFiles_DEFAULT *MediaFiles

func (p *UploadFileResultDto) GetMediaFiles() (v *MediaFiles) {
	if !p.IsSetMediaFiles() {
		return UploadFileResultDto_MediaFiles_DEFAULT
	}
	return p.MediaFiles
}
func (p *UploadFileResultDto) SetMediaFiles(val *MediaFiles) {
	p.MediaFiles = val
}

var fieldIDToName_UploadFileResultDto = map[int16]string{
	1: "mediaFiles",
}

func (p *UploadFileResultDto) IsSetMediaFiles() bool {
	return p.MediaFiles != nil
}

func (p *UploadFileResultDto) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_UploadFileResultDto[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *UploadFileResultDto) ReadField1(iprot thrift.TProtocol) error {
	p.MediaFiles = NewMediaFiles()
	if err := p.MediaFiles.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *UploadFileResultDto) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UploadFileResultDto"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *UploadFileResultDto) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("mediaFiles", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.MediaFiles.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *UploadFileResultDto) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UploadFileResultDto(%+v)", *p)

}

func (p *UploadFileResultDto) DeepEqual(ano *UploadFileResultDto) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.MediaFiles) {
		return false
	}
	return true
}

func (p *UploadFileResultDto) Field1DeepEqual(src *MediaFiles) bool {

	if !p.MediaFiles.DeepEqual(src) {
		return false
	}
	return true
}

type Media interface {
	QueryMediaFiles(ctx context.Context, req *PageParams) (r *PageResult_, err error)

	UploadMediaFiles(ctx context.Context, req *UploadFileParamsDto, filePath string) (r *UploadFileResultDto, err error)
}

type MediaClient struct {
	c thrift.TClient
}

func NewMediaClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *MediaClient {
	return &MediaClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewMediaClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *MediaClient {
	return &MediaClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewMediaClient(c thrift.TClient) *MediaClient {
	return &MediaClient{
		c: c,
	}
}

func (p *MediaClient) Client_() thrift.TClient {
	return p.c
}

func (p *MediaClient) QueryMediaFiles(ctx context.Context, req *PageParams) (r *PageResult_, err error) {
	var _args MediaQueryMediaFilesArgs
	_args.Req = req
	var _result MediaQueryMediaFilesResult
	if err = p.Client_().Call(ctx, "QueryMediaFiles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *MediaClient) UploadMediaFiles(ctx context.Context, req *UploadFileParamsDto, filePath string) (r *UploadFileResultDto, err error) {
	var _args MediaUploadMediaFilesArgs
	_args.Req = req
	_args.FilePath = filePath
	var _result MediaUploadMediaFilesResult
	if err = p.Client_().Call(ctx, "UploadMediaFiles", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type MediaProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      Media
}

func (p *MediaProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *MediaProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *MediaProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewMediaProcessor(handler Media) *MediaProcessor {
	self := &MediaProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("QueryMediaFiles", &mediaProcessorQueryMediaFiles{handler: handler})
	self.AddToProcessorMap("UploadMediaFiles", &mediaProcessorUploadMediaFiles{handler: handler})
	return self
}
func (p *MediaProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type mediaProcessorQueryMediaFiles struct {
	handler Media
}

func (p *mediaProcessorQueryMediaFiles) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MediaQueryMediaFilesArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("QueryMediaFiles", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MediaQueryMediaFilesResult{}
	var retval *PageResult_
	if retval, err2 = p.handler.QueryMediaFiles(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing QueryMediaFiles: "+err2.Error())
		oprot.WriteMessageBegin("QueryMediaFiles", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("QueryMediaFiles", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type mediaProcessorUploadMediaFiles struct {
	handler Media
}

func (p *mediaProcessorUploadMediaFiles) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := MediaUploadMediaFilesArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("UploadMediaFiles", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := MediaUploadMediaFilesResult{}
	var retval *UploadFileResultDto
	if retval, err2 = p.handler.UploadMediaFiles(ctx, args.Req, args.FilePath); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing UploadMediaFiles: "+err2.Error())
		oprot.WriteMessageBegin("UploadMediaFiles", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("UploadMediaFiles", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type MediaQueryMediaFilesArgs struct {
	Req *PageParams `thrift:"req,1" frugal:"1,default,PageParams" json:"req"`
}

func NewMediaQueryMediaFilesArgs() *MediaQueryMediaFilesArgs {
	return &MediaQueryMediaFilesArgs{}
}

func (p *MediaQueryMediaFilesArgs) InitDefault() {
	*p = MediaQueryMediaFilesArgs{}
}

var MediaQueryMediaFilesArgs_Req_DEFAULT *PageParams

func (p *MediaQueryMediaFilesArgs) GetReq() (v *PageParams) {
	if !p.IsSetReq() {
		return MediaQueryMediaFilesArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *MediaQueryMediaFilesArgs) SetReq(val *PageParams) {
	p.Req = val
}

var fieldIDToName_MediaQueryMediaFilesArgs = map[int16]string{
	1: "req",
}

func (p *MediaQueryMediaFilesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MediaQueryMediaFilesArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MediaQueryMediaFilesArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MediaQueryMediaFilesArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewPageParams()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MediaQueryMediaFilesArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("QueryMediaFiles_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MediaQueryMediaFilesArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MediaQueryMediaFilesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MediaQueryMediaFilesArgs(%+v)", *p)

}

func (p *MediaQueryMediaFilesArgs) DeepEqual(ano *MediaQueryMediaFilesArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	return true
}

func (p *MediaQueryMediaFilesArgs) Field1DeepEqual(src *PageParams) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}

type MediaQueryMediaFilesResult struct {
	Success *PageResult_ `thrift:"success,0,optional" frugal:"0,optional,PageResult_" json:"success,omitempty"`
}

func NewMediaQueryMediaFilesResult() *MediaQueryMediaFilesResult {
	return &MediaQueryMediaFilesResult{}
}

func (p *MediaQueryMediaFilesResult) InitDefault() {
	*p = MediaQueryMediaFilesResult{}
}

var MediaQueryMediaFilesResult_Success_DEFAULT *PageResult_

func (p *MediaQueryMediaFilesResult) GetSuccess() (v *PageResult_) {
	if !p.IsSetSuccess() {
		return MediaQueryMediaFilesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MediaQueryMediaFilesResult) SetSuccess(x interface{}) {
	p.Success = x.(*PageResult_)
}

var fieldIDToName_MediaQueryMediaFilesResult = map[int16]string{
	0: "success",
}

func (p *MediaQueryMediaFilesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MediaQueryMediaFilesResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MediaQueryMediaFilesResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MediaQueryMediaFilesResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewPageResult_()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MediaQueryMediaFilesResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("QueryMediaFiles_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MediaQueryMediaFilesResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MediaQueryMediaFilesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MediaQueryMediaFilesResult(%+v)", *p)

}

func (p *MediaQueryMediaFilesResult) DeepEqual(ano *MediaQueryMediaFilesResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MediaQueryMediaFilesResult) Field0DeepEqual(src *PageResult_) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}

type MediaUploadMediaFilesArgs struct {
	Req      *UploadFileParamsDto `thrift:"req,1" frugal:"1,default,UploadFileParamsDto" json:"req"`
	FilePath string               `thrift:"filePath,2" frugal:"2,default,string" json:"filePath"`
}

func NewMediaUploadMediaFilesArgs() *MediaUploadMediaFilesArgs {
	return &MediaUploadMediaFilesArgs{}
}

func (p *MediaUploadMediaFilesArgs) InitDefault() {
	*p = MediaUploadMediaFilesArgs{}
}

var MediaUploadMediaFilesArgs_Req_DEFAULT *UploadFileParamsDto

func (p *MediaUploadMediaFilesArgs) GetReq() (v *UploadFileParamsDto) {
	if !p.IsSetReq() {
		return MediaUploadMediaFilesArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *MediaUploadMediaFilesArgs) GetFilePath() (v string) {
	return p.FilePath
}
func (p *MediaUploadMediaFilesArgs) SetReq(val *UploadFileParamsDto) {
	p.Req = val
}
func (p *MediaUploadMediaFilesArgs) SetFilePath(val string) {
	p.FilePath = val
}

var fieldIDToName_MediaUploadMediaFilesArgs = map[int16]string{
	1: "req",
	2: "filePath",
}

func (p *MediaUploadMediaFilesArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *MediaUploadMediaFilesArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MediaUploadMediaFilesArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MediaUploadMediaFilesArgs) ReadField1(iprot thrift.TProtocol) error {
	p.Req = NewUploadFileParamsDto()
	if err := p.Req.Read(iprot); err != nil {
		return err
	}
	return nil
}
func (p *MediaUploadMediaFilesArgs) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.FilePath = v
	}
	return nil
}

func (p *MediaUploadMediaFilesArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UploadMediaFiles_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MediaUploadMediaFilesArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *MediaUploadMediaFilesArgs) writeField2(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("filePath", thrift.STRING, 2); err != nil {
		goto WriteFieldBeginError
	}
	if err := oprot.WriteString(p.FilePath); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *MediaUploadMediaFilesArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MediaUploadMediaFilesArgs(%+v)", *p)

}

func (p *MediaUploadMediaFilesArgs) DeepEqual(ano *MediaUploadMediaFilesArgs) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field1DeepEqual(ano.Req) {
		return false
	}
	if !p.Field2DeepEqual(ano.FilePath) {
		return false
	}
	return true
}

func (p *MediaUploadMediaFilesArgs) Field1DeepEqual(src *UploadFileParamsDto) bool {

	if !p.Req.DeepEqual(src) {
		return false
	}
	return true
}
func (p *MediaUploadMediaFilesArgs) Field2DeepEqual(src string) bool {

	if strings.Compare(p.FilePath, src) != 0 {
		return false
	}
	return true
}

type MediaUploadMediaFilesResult struct {
	Success *UploadFileResultDto `thrift:"success,0,optional" frugal:"0,optional,UploadFileResultDto" json:"success,omitempty"`
}

func NewMediaUploadMediaFilesResult() *MediaUploadMediaFilesResult {
	return &MediaUploadMediaFilesResult{}
}

func (p *MediaUploadMediaFilesResult) InitDefault() {
	*p = MediaUploadMediaFilesResult{}
}

var MediaUploadMediaFilesResult_Success_DEFAULT *UploadFileResultDto

func (p *MediaUploadMediaFilesResult) GetSuccess() (v *UploadFileResultDto) {
	if !p.IsSetSuccess() {
		return MediaUploadMediaFilesResult_Success_DEFAULT
	}
	return p.Success
}
func (p *MediaUploadMediaFilesResult) SetSuccess(x interface{}) {
	p.Success = x.(*UploadFileResultDto)
}

var fieldIDToName_MediaUploadMediaFilesResult = map[int16]string{
	0: "success",
}

func (p *MediaUploadMediaFilesResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *MediaUploadMediaFilesResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_MediaUploadMediaFilesResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *MediaUploadMediaFilesResult) ReadField0(iprot thrift.TProtocol) error {
	p.Success = NewUploadFileResultDto()
	if err := p.Success.Read(iprot); err != nil {
		return err
	}
	return nil
}

func (p *MediaUploadMediaFilesResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("UploadMediaFiles_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *MediaUploadMediaFilesResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *MediaUploadMediaFilesResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MediaUploadMediaFilesResult(%+v)", *p)

}

func (p *MediaUploadMediaFilesResult) DeepEqual(ano *MediaUploadMediaFilesResult) bool {
	if p == ano {
		return true
	} else if p == nil || ano == nil {
		return false
	}
	if !p.Field0DeepEqual(ano.Success) {
		return false
	}
	return true
}

func (p *MediaUploadMediaFilesResult) Field0DeepEqual(src *UploadFileResultDto) bool {

	if !p.Success.DeepEqual(src) {
		return false
	}
	return true
}
